// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SleepTracker.Data;

#nullable disable

namespace SleepTracker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SleepTracker.Models.SleepSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("SleepQuality")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("SleepTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("WakeUpTime")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SleepSessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Dobry sen, bez pobudek",
                            SleepQuality = 4,
                            SleepTime = new TimeSpan(0, 23, 0, 0, 0),
                            WakeUpTime = new TimeSpan(0, 6, 30, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 4, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Zbyt późno spać, zmęczenie rano",
                            SleepQuality = 2,
                            SleepTime = new TimeSpan(0, 0, 30, 0, 0),
                            WakeUpTime = new TimeSpan(0, 7, 45, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Notes = "Najlepszy sen w tygodniu!",
                            SleepQuality = 5,
                            SleepTime = new TimeSpan(0, 22, 45, 0, 0),
                            WakeUpTime = new TimeSpan(0, 6, 0, 0, 0)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
